version: '3.9'

services:
  app:
    depends_on:
      - redis
      - app-db
    build: ./
    restart: on-failure
    environment:
      PORT:
      DATABASE:
      DATABASE_PORT:
      DATABASE_HOST:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
      SESSION_SECRET:
      REDIS_PORT:
      REDIS_PASSWORD:
      REDIS_HOST:
    ports:
      - target: 4000
        published: 4000
        protocol: tcp
        mode: host
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - ./public/uploads:./uploads
  redis:
    image: redis:7.0.8-bullseye
    restart: always
  app-db:
    image: postgres:13-bullseye
    restart: always
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - app_db_data:/var/lib/postgresql/data

  upload-db:
    image: postgres:13-bullseye
    restart: always
    environment:
      POSTGRES_DB: 'upload-layer'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '@mir1990'
    volumes:
      - upload_db_data:/var/lib/postgresql/data

volumes:
  app_db_data:
    driver: local
  upload_db_data:
    driver: local
