version: '3.9'

services:
  app:
    depends_on:
      - redis
      - postgres
    build: ./
    restart: on-failure
    environment:
      PORT:
      DATABASE:
      DATABASE_PORT:
      DATABASE_HOST:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
      SESSION_SECRET:
      REDIS_PORT:
      REDIS_PASSWORD:
      REDIS_HOST:
    ports:
      - 4000:4000
  redis:
    image: redis:latest
    restart: always
    environment:
      REDIS_PASSWORD:
    ports:
      - 6379:6379
  postgres:
    image: postgres:13-bullseye
    restart: always
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  uploads:
    depends_on:
      - redis
      - postgres
      # - backend
    image: node:18.12.1-slim
    volumes:
      - upload_storage:/app/upload-storage

volumes:
  db_data:
    driver: local
  upload_storage:
    external: true
